### ISSUE TITLE
Design the front-end part of the project!

### ISSUE THREAD

**Issue by tsarchghs** [gjergjk71/jCoders-WebApp#1]
It doesn't have to be anything special or even your design ( as long as you find an open-source one ), I'd just love having a front-end developer contributing to this project since I'm more back-end focused. Until now I've just been using bootstrap examples from docs.

**Comment by RafaelBroseghini** [comment]
What are you thinking? It does not look bad from my perspective but I can certainly help you.

**Comment by tsarchghs** [comment]
@RafaelBroseghini I'd like to change the look of Login/Forgot Password for a start, I don't think it's bad either but every project I've done until now screams "the same old bootstrap examples Gjergj!"

**Comment by RafaelBroseghini** [comment]
@gjergjk71 have you ever heard of Semantic UI? I can help you with that. I can make something nice. Would you like to use a CDN version of Semantic UI or a local dist?

**Comment by tsarchghs** [comment]
@RafaelBroseghini CDN version

**Comment by RafaelBroseghini** [comment]
Also, I noticed you have all your css and javascript/jquery within the templates. How do you feel about moving them to specific: css and js folders?

**Comment by tsarchghs** [comment]
Yeah, it's an eyesore. You can work on the login/forgot password I'll work on issue #4 and configure django settings for static css/js.
